export const routes = {
  ACIVITIESDETAIL: "/actividades/:id",
  ACTIVITIESFORM: "/create-activity",
  AUTHLOGINFORM: "/auth/login",
  AUTHREGISTERFORM: "/auth/register",
  CONTACTUS: "/contact-us",
  DONATION: "/donar",
  HOME: "/",
  MEMBERSFORM: "/create-member",
  NEWSDETAIL: "/novedades/:id",
  NEWSFORM: "/create-news",
  ORGANIZATIONDATA: "/backoffice/organization",
  PROJECTFORM: "/create-project",
  SLIDERSFORM: "/backoffice/create-slide",
  SCHOOLCAMPAIGN: "/school-campaign",
  TESTIMONIALSFORM: "/create-testimonials",
  THANKSDONATION: "/gracias",
  TOYSCAMPAIGN: "/toys-campaign",
};

export const privateRoutes = {
  ACTIVITIESFORM: "activities",
  ACTIVITIESEDITFORM: "activities/:id",
  BACKOFFICE: "backoffice",
  EDITMEMBERSFORM: "members/edit",
  CREATECATEGORY: "create-category",
  EDITCATEGORY: "edit-category/:id",
  EDITORGANIZATIONFORM: "organization/edit",
  SLIDES: "slides",
  SLIDESWITHID: "slides/:id",
  TESTIMONIALSFORM: "testimonials",
  TESTIMONIALSEDITFORM: "testimonials/:id",
};
