export const routes = {
  ACTIVITIES: "/actividades",
  ACIVITIESDETAIL: "/actividades/:id",
  ACTIVITIESFORM: "/create-activity",
  AUTHLOGINFORM: "/auth/login",
  AUTHREGISTERFORM: "/auth/register",
  CONTACT: "/contact",
  DONATION: "/donar",
  HOME: "/",
  MEMBERSFORM: "/create-member",
  NEWS: "/novedades",
  NEWSDETAIL: "/novedades/:id",
  NEWSFORM: "/create-news",
  ORGANIZATIONDATA: "/backoffice/organization",
  PROJECTFORM: "/create-project",
  SCHOOLCAMPAIGN: "/school-campaign",
  TESTIMONIALSFORM: "/create-testimonials",
  THANKSDONATION: "/gracias",
  TOYSCAMPAIGN: "/toys-campaign",
};

export const privateRoutes = {
  ACTIVITIESEDITFORM: "activities/:id",
  ACTIVITIESFORM: "activities",
  BACKOFFICE: "backoffice/",
  BACKHOME: "home",
  CREATECATEGORY: "create-category",
  CREATEPROJECT: "projects",
  EDITCATEGORY: "edit-category/:id",
  EDITMEMBERSFORM: "members/edit",
  EDITORGANIZATIONFORM: "organization/edit",
  EDITPROJECT: "projects/:id",
  NEWSEDITFORM: "news/:id",
  NEWSFORM: "news",
  SLIDES: "slides",
  SLIDESWITHID: "slides/:id",
  TESTIMONIALSFORM: "testimonials",
  TESTIMONIALSEDITFORM: "testimonials/:id",
  USERSFORM: "users",
  USERSEDITFORM: "users/:id"
};
