export const routes = {
  HOME: "/",
  ACTIVITIESFORM: "/create-activity",
  AUTHLOGINFORM: "/auth/login",
  AUTHREGISTERFORM: "/auth/register",
  CATEGORIESFORM: "/create-category",
  EDITORGANIZATIONFORM: "/backoffice/organization/edit",
  NEWSFORM: "/create-news",
  SLIDERSFORM: "/backoffice/create-slide",
  TESTIMONIALSFORM: "/create-testimonials",
  USERFORM: "/create-user",
  MEMBERSFORM: "/create-member",
  PROJECTFORM: "/create-project",
  SCHOOLCAMPAIGN: "/school-campaign",
  TOYSCAMPAIGN: "/toys-campaign",
  NEWSDETAIL: "/novedades/:id",
  CONTACTUS: "/contact-us",
};
